### PR TITLE
Add support for training custom EMLE models

### PR DESCRIPTION
**Pull request by lohedges**
This PR adds support for training EMLE models and supersedes #35. In comparison to #35 I have:

* Made the code work with TorchScript.
* Fixed several minor bugs.
* Improved input validation on class instantiation.
* Added docstrings throughput and standardised formatting.
* Refactored a few classes.
* Applied autoformatting throughout.
* Store inputs to the `EMLE.forward` method as private class attributes, e.g. `self._atomic` numbers, etc.

@kzinovjev and @JMorado: Many thanks for this, it is great. I've run the unit tests locally and have also checked that `sire-emle` works as expected. The code here requires an updated model file so the CI will fail. I'll upload the new one once we're happy. Some things that I'd like you to add/check before merging:

* Please check that the analysis and training scripts still work as expected. These aren't (yet) covered by the tests, so I haven't run them.
* Please check the new docstrings. Some of these were partially auto-generated, so they might not be 100% correct. Important things are the shapes for tensors and the meaning of the return values. I have added them throughput, but the `train` sub-package has the most additions.
* Can we add short sections to the `README.md` file to explain how to use the new `emle-anayze` and `emle-train` executables? These don't need to be super long, but should cover the basics. Regarding this, I think we're getting to the point where it would be useful to create a static website via GitHub pages so that we can format things nicely and add proper sectioning. (This can be done in another PR at a later date.)
* Possibly change print statements in the training and analyser routines to logging using `loguru`. That way you could add more debugging info if needed and suppress the output by default via the log-level.

Let me know if you have any questions about any of the edits. Feel free to suggest changes via Slack, or merge this into your own fork and make any updates that are needed. I  can re-review in the other PR.

Cheers,
Lester

### CODE REVIEW

**Comment by JMorado** [comment]
Many thanks for this, @lohedges.

@kzinovjev, since you coded the executables, would you be OK to write the README for that part? I’m happy to handle the logging.

Also, should PR #35 be reopened? We’ve been committing to the `emle-train` branch on Kirill’s fork.

**Comment by kzinovjev** [comment]
@JMorado sure, the CLI section is on me, will get to it next week. I am done debugging the training script, still have to check the analysis one. 
Regarding PR https://github.com/chemle/emle-engine/pull/35 I closed it for now, but can reopen once we are done with the changes.

**Comment by lohedges** [comment]
> Regarding PR https://github.com/chemle/emle-engine/pull/35 I closed it for now, but can reopen once we are done with the changes.

I can also merge your changes back into this branch when we're done. That might be simpler as I'll probably do some final checks at my end.

**Comment by lohedges** [comment]
I'll also start work on a static GitHub pages website once were done with this. I'll copy across the contents from the README and add some API docs. Then we can add some expanded tutorials for how to train models and run simulations.

**Pull request merged**
